version: "3"

services:
  phpapache:
    image: custom_php
    ports:
      - "80:80"
    volumes:
      - "./src/:/var/www/html"
    command: sh -c "Le serveur est disponible sur localhost:80 ou localhost. Attendez quelques minutes pour que la DB se mette en route. Vous pouvez également visiter PHP My Admin sur localhost:8081"
  
  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=mysqldb
      - MYSQL_ROOT_PASSWORD=oui
    volumes:
      - "./sql/:/docker-entrypoint-initdb.d"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=oui
